### ISSUE TITLE
[Enhancement] Improve ConfigManager Error Handling and Robustness

### ISSUE THREAD

**Issue by VitalikObject** [itzmew/TicTacToe#1]
The ConfigManager class currently has several areas for potential improvement related to error handling and robustness. Here are some issues and suggestions:

### 1. Error Handling for File Operations:

   * When opening or reading from a file fails, the class defaults to hardcoded values without providing any feedback or error reporting. It would be beneficial to include error messages or logging to inform users of issues.
### 2. Empty File Handling:

   * The current implementation sets default values if the configuration file is empty or cannot be opened. This behavior is not always desirable and should be documented or made configurable.
### 3. File Path Validation:

   * The class does not validate the file path before attempting to open it. Adding file path validation could prevent errors related to invalid paths.
### 4. Config Parsing Robustness:

   * The parsing logic assumes each line is in the key=value format without checking for malformed lines. Adding checks or error handling for invalid or unexpected line formats would make the parser more robust.
### 5. Thread Safety:

   * The current implementation does not handle concurrent access, which could be an issue in multithreaded applications. Consider adding thread safety mechanisms if this class will be used in such contexts.
### 6. Efficiency Improvements:

   * Switching from std::map to std::unordered_map for configuration storage might offer performance benefits due to average constant-time complexity for insertions and lookups.
### Proposed Solution:

* Add error handling for file operations with appropriate error messages.
* Consider adding options or documentation for handling empty configuration files.
* Implement validation for the file path.
* Enhance the configuration parsing logic to handle malformed lines gracefully.
* If applicable, add thread safety measures.
* Replace std::map with std::unordered_map for better performance if the order of entries is not critical.

### Additional Context:

The current implementation provides default values if issues arise during file operations or if the file is empty. However, enhancing the robustness of the configuration manager will improve its reliability and usability in different scenarios.

**Comment by itzmew** [comment]
Thank you for your detailed review and suggestions regarding the ConfigManager class. I appreciate your insights, and I'll address each of your points.
